"""cues.py — Cue-based fact categorization, self-containment repair, and dedup."""

import re

from .utils import compile_boundary_pattern


# ─── Category cue phrases (data-driven) ───────────────────────────────────────

_CUE_DEFS: dict[str, list[str]] = {
    "identity": [
        "project name is", "next project name is", "repo name is",
        "repository name is", "called", "named",
    ],
    "convention": [
        "should be named", "must be named", "always name", "never name",
        "always use", "never use", "don't use", "do not use",
        "prefer(?:\\s+to)?", "recommended", "best practice", "convention",
        "naming convention", "style rule", "coding standard",
        "must follow", "should follow",
        "going forward", "from now on", "hereafter",
        "keep using", "continue using",
        "all files should", "every file should",
        "every function should", "all functions should",
        "always call", "always inject", "always store", "always return",
        "always validate", "always strip",
        "must always", "should always", "must never", "should never",
    ],
    "decision": [
        "decided(?:\\s+to|\\s+on)?", "decision(?:\\s+was)?", "going with",
        "we(?:'ll| will)? use", "we(?:'ll| will)? keep",
        "we(?:'ll| will)? stick with", "we(?:'ll| will)? switch to",
        "we(?:'ll| will)? migrate to", "we(?:'ll| will)? move to",
        "we(?:'ll| will)? adopt", "we(?:'ll| will)? implement",
        "we(?:'ll| will)? store", "we(?:'ll| will)? save",
        "we(?:'ll| will)? inject", "we(?:'ll| will)? call",
        "we(?:'ll| will)? expose", "we(?:'ll| will)? create",
        "we(?:'ll| will)? remove", "we(?:'ll| will)? rename",
        "we(?:'ll| will)? refactor",
        "chose", "choosing", "choice(?:\\s+is)?", "opted(?:\\s+for)?",
        "settled(?:\\s+on)?", "selected", "picked", "preferred?",
        "standardized on", "committed to", "agreed(?:\\s+to|\\s+on)?",
        "the plan is to", "the approach is", "the solution is", "the fix is",
        "the design is", "the architecture is",
        "instead of", "rather than", "replace(?:d)? with", "swap(?:ped)? to",
        "use(?:d)? instead", "keep using", "continue using",
    ],
    "goal": [
        "I want to", "I'm going to", "I plan to",
        "trying to", "learning", "studying", "goal is", "objective is",
    ],
    "open_thread": [
        "todo", "to-do", "fixme", "xxx", "hack", "temporary", "workaround",
        "unresolved",
        "still need to", "need to", "needs to",
        "remaining", "left to do", "follow[- ]?up", "future work",
        "not yet(?:\\s+implemented|\\s+decided|\\s+finished)?",
        "pending", "known bug", "known issue",
        "bug", "issue", "edge case", "fails when",
        "doesn't work", "does not work", "broken", "missing", "incomplete",
        "blocked by", "waiting for",
        "need to investigate", "need to verify", "need to figure out",
        "unclear(?:\\s+whether|\\s+how)?", "unknown", "question is",
        "haven't decided", "haven't implemented", "hasn't been done",
    ],
    "architecture": [
        "architecture", "design", "pipeline", "workflow",
        "request flow", "response flow", "proxy", "wrapper",
        "middleware", "hook", "lifecycle", "startup", "shutdown",
        "dependency injection", "session lifecycle",
        "data flow", "control flow",
    ],
    "api": [
        "endpoint", "route", "api", "request", "response",
        "payload", "body", "json", "header", "status code",
        "GET", "POST", "PUT", "PATCH", "DELETE",
        "/v1/", "http://", "https://",
    ],
    "database": [
        "sqlite", "postgres", "database", "schema", "table",
        "column", "row", "index", "migration", "dataset",
        "cognee", "vector", "embedding", "knowledge graph",
        "remember", "recall", "forget", "improve",
    ],
    "implementation": [
        "file", "module", "package", "directory", "folder",
        "class", "function", "method", "variable",
        r"app\.", r"main\.py", r"memory\.py", r"proxy\.py",
        r"filter\.py", r"config\.py", r"session\.py",
        "README", r"\.env",
    ],
    "state": [
        "currently", "now", "today", "is now",
        "exists(?:\\s+at)?",
        "is located at", "lives in", "resides in",
        "is stored in", "is saved in", "is cached in",
        "is persisted in", "is indexed by", "is backed by",
        "is implemented(?:\\s+as|\\s+in)?",
        "is defined in", "is declared in",
        "is exposed at", "is available at",
        "is handled by", "is managed by",
        "is called from", "is invoked by",
        "is generated by", "is created by",
        "contains", "includes", "consists of",
        "uses", "depends on", "relies on",
        "runs on", "listens on", "maps to", "points to",
        "returns", "accepts", "expects", "supports",
        "tracks", "stores", "loads", "reads from", "writes to",
        "the schema(?:\\s+has|\\s+includes)?",
        "the database(?:\\s+has|\\s+contains)?",
        "the table(?:\\s+has|\\s+contains)?",
        "the endpoint(?:\\s+is)?", "the route(?:\\s+is)?",
        r"the file .*?(?:contains|has|defines)",
        r"the function .*?(?:returns|accepts|calls)",
        r"the class .*?(?:contains|implements)",
    ],
}

CUE_PATTERNS: dict[str, re.Pattern] = {
    cat: compile_boundary_pattern(fragments)
    for cat, fragments in _CUE_DEFS.items()
}

_RESOLVED_CUE_WORDS: list[str] = [
    "fixed", "resolved", "solved", "completed", "implemented",
    "finished", "done", "working", "verified", "confirmed",
    "validated", "addressed", "patched", "merged", "closed",
    "removed", "eliminated", "cleaned up", "refactored",
    "figured out", "no longer(?:\\s+an)? issue",
    "works now", "passes", "successfully",
]

_RESOLVED_CUES: re.Pattern = compile_boundary_pattern(_RESOLVED_CUE_WORDS)

_PRONOUN_RE: re.Pattern = re.compile(
    r"\b(it|this|that|these|those|they|he|she|him|her|its|their)\b",
    re.IGNORECASE,
)


# ─── Sentence utilities ───────────────────────────────────────────────────────

def split_sentences(text: str) -> list[str]:
    """Split text into sentences on standard punctuation boundaries."""
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s.strip()]


def _has_dangling_pronoun(sentence: str) -> bool:
    """Check if a sentence starts with a pronoun (after stripping filler words)."""
    working = re.sub(
        r"^(yes|no|sure|ok|okay|well|so|right)\s*,?\s*",
        "", sentence.strip(), flags=re.IGNORECASE,
    )
    first_word = working.split(" ", 1)[0].lower().strip(",.!?") if working else ""
    return first_word in {"it", "this", "that", "these", "those", "they", "he", "she"}


# ─── Categorization ───────────────────────────────────────────────────────────

def categorize_sentence(sentence: str) -> str | None:
    """Classify a sentence into a fact category based on cue phrases."""
    for category, pattern in CUE_PATTERNS.items():
        if pattern.search(sentence):
            if category == "open_thread" and _RESOLVED_CUES.search(sentence):
                continue
            return category
    return None


# ─── Self-containment repair ──────────────────────────────────────────────────

def make_self_contained(sentence: str, topic_subject: str) -> str | None:
    """Rewrite a sentence to remove dangling pronoun references.

    Returns ``None`` if the sentence cannot be safely repaired.
    """
    if not _has_dangling_pronoun(sentence):
        return sentence

    if not topic_subject:
        return None

    working = re.sub(
        r"^(yes|no|sure|ok|okay|well|so|right)\s*,?\s*",
        "", sentence, flags=re.IGNORECASE,
    )

    m = re.match(
        r"^(it|this|that|these|those|they)\s+(is|was|are|were)\s+(.*)$",
        working, flags=re.IGNORECASE,
    )
    if not m:
        return None

    verb, rest = m.group(2), m.group(3)

    # Guard against rewriting ungrammatical source text
    broken_rest = re.match(
        r"^(still |also |now |currently )?(need to|going to|able to|trying to)\b",
        rest, flags=re.IGNORECASE,
    )
    if broken_rest:
        return None

    repaired = f"{topic_subject} {verb} {rest}".strip()
    repaired = repaired[0].upper() + repaired[1:] if repaired else repaired

    if _has_dangling_pronoun(repaired):
        return None

    return repaired


def derive_topic_subject(user_text: str) -> str:
    """Extract a short noun-phrase subject from a user question."""
    cleaned = re.sub(
        r"^(why|what|how|when|where|which|who|should|can|does|do|is|are|would)\b",
        "", user_text.strip(), flags=re.IGNORECASE,
    ).strip(" ?.!")
    words = cleaned.split()
    return " ".join(words[:8]) if words else ""


# ─── Deduplication ────────────────────────────────────────────────────────────

def _normalize_for_dedup(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9 ]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def dedup_facts(facts: list[dict]) -> list[dict]:
    """Collapse duplicate/near-duplicate facts within the same session."""
    seen: list[tuple[str, set[str]]] = []
    out = []
    for fact in facts:
        norm = _normalize_for_dedup(fact["text"])
        norm_tokens = set(norm.split())
        is_dup = False
        for _, seen_tokens in seen:
            if not seen_tokens or not norm_tokens:
                continue
            overlap = len(norm_tokens & seen_tokens) / max(len(norm_tokens), len(seen_tokens))
            if overlap >= 0.8:
                is_dup = True
                break
        if not is_dup:
            seen.append((norm, norm_tokens))
            out.append(fact)
    return out
